#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "Checking types..."
tsc --noEmit --project tsconfig.lint.json

echo "Linting..."
ng lint --fix

echo "Running tests..."
ng test --watch=false --browsers=ChromeHeadlessNoSandbox --code-coverage
